apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: java-quarkus-sample
  namespace: karthik-jk
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: test
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: java-quarkus-sample
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: java-quarkus-sample-
      labels:
        build.appstudio.openshift.io/application: test
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: java-quarkus-sample
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: karthik-jk
    spec:
      params:
      - name: git-url
        value: https://github.com/devfile-samples/devfile-sample-code-with-quarkus.git
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:karthik-jk-java-quarkus-sample-$(tt.params.git-revision)
      - name: dockerfile
        value: src/main/docker/Dockerfile.jvm.staged
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/hacbs-templates-bundle:latest
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: java-quarkus-sample/$(tt.params.git-revision)
    status: {}
status: {}
